# Pamplona 2020
#  Playbook which stops databases
---
- name: "stopping {{oracle_sid}} database"
  set_fact:
    shutted_down: false
 
- name: "Logging   {{oracle_sid}}"
  blockinfile:
    path: "{{logfile}}"
    marker: ""
    insertafter: EOF
    block: |
        #--------------------- shutting down {{oracle_sid}}  -----------------------
  when: activo|bool

- include: tasks/srvctl_db_shutdown.yml
  when: activo|bool

- include: tasks/check_running_SID.yml
  when: activo|bool

- include: tasks/sqlplus_db_shutdown.yml
  when: activo|bool  and not shutted_down |bool
