# Pamplona 2020
#  Playbook which stop active lsteners 
---
- name: "setting var {{shutted_down}} at listener {{item}}"
  set_fact:
    shutted_down: false

- name : "stopping {{item}}  with srvctl"
  shell:  "{{oracle_home}}/bin/srvctl stop listener -listener  {{item}}"
  register: command_output
  environment:
    ORACLE_HOME: "{{oracle_home}}"
    PATH: "$PATH:${{oracle_home}}:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:${{oracle_home}}/lib"
  ignore_errors: true 
 
- name: "logging srvctl status for {{item}}"
  blockinfile:
    path: "{{logfile}}"
    marker: ""  
    insertafter: EOF
    block: |
      #--- stopping listener  {{item}} ------
         {{command_output.stdout}}
         {{command_output.stderr}}
- name : "check if {{item}} is running "
  shell: "ps -ef |grep -v grep |grep -w {{item}}"
  environment:
    PATH: "$PATH:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
  ignore_errors: yes
  register: sid_running

- name: setting shutted_down variable after first try 
  set_fact:
    shutted_down: true
  when: "{{ sid_running.stdout_lines|length }} == 0"

- name : "stopping listener {{item}}  with full command"
  shell:  "{{oracle_home}}/bin/lsnrctl  stop  {{item}}"
  register: command_output
  environment:
    ORACLE_HOME: "{{oracle_home}}"
    PATH: "$PATH:${{oracle_home}}:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:${{oracle_home}}/lib"
  
  ignore_errors: true
  when: not shutted_down |bool

- name: "registering {{oracle_home}}/bin/lsnrctl  stop  {{item}} output & error at log"
  blockinfile:
      path: "{{logfile}}"
      marker: ""
      insertafter: EOF
      block: |
             {{command_output.stdout}}
             {{command_output.stderr}}
  when: not shutted_down|bool


