# Pamplona 2020
#  Playbook which start active databases with srvctl 
---
- name : "starting {{item}} with srvctl"
  shell: "{{oracle_home}}/bin/srvctl start database -db {{oracle_sid}} "
  register: command_output
  environment:
    ORACLE_HOME: "{{oracle_home}}"
    ORACLE_SID:  "{{oracle_sid}}"
    PATH: "$PATH:${{oracle_home}}:/bin:/usr/bin:/bin:/usr/local/bin:/sbin"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:${{oracle_home}}/lib"
  ignore_errors: true 
  
- name: registering srvctl start   information 
  blockinfile:
    path: "{{logfile}}"
    marker: ""
    insertafter: EOF
    block: |
       {{command_output.stdout}}
       {{command_output.stderr}}
 
