
# Pamplona 2020-04
#  Playbook wich stop all oracle services in an standalone server 
#  
#  requires
#    env:      name of the server  which should be in the inventory
#    req:      number of request for the backout 
#    operation:   Action to be done [stop|start]
#
---
- hosts: "{{ env }}"
  vars:
    operation: start
  vars_files:
    - "vars/main.yml"
  remote_user: "{{ansible_user}}"
  pre_tasks:
  # Checking if we have the required variables
   - fail: 
        msg: | 
         ERROR:   please lease check variables:
             env:   name of the server  which should be in the inventory
             req:    number of request for the backout  env,  req  in the job
             operation 
     when:  item  is not defined
     with_items:
      - env 
      - req
      - operation 
 
  roles:
    - { role: standalone_stop_start ,become: yes, become_user: "{{oracle_user}}" }